name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker container
        id: docker
        uses: docker/build-push-action@v4
        with:
          context: ./container/
          file: container/Dockerfile
          load: true
          push: false
          tags: ${{ github.repository }}:latest
      - name: Test container with simple dataset
        run: |
          docker run --rm -t ${{ github.repository }}:latest -e JAVA_OPTS="-Xms3g -Xmx4g" -w ./container/test-instances:/tests tests/hc-power-11.col tests/hc-power-11_01.dat
        env:
          MEM_LIMII_GB: 7

  test-description:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: description
          root_file: main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: Description
          path: description/main.pdf
