name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker container
        id: docker
        uses: docker/build-push-action@v4
        with:
          context: ./container/
          file: container/Dockerfile
          load: true
          push: false
          tags: ${{ github.repository }}:latest
      - name: Set environment variables for your solver
        run: |
          echo JAVA_OPTS="-Xms${MEM_LIMIT_GB}g -Xmx${MEM_LIMIT_GB}g" > .env
        env:
          MEM_LIMIT_GB: 7 # memory limit for Github hosted runner
      # - name: Test container with simple dataset
      #   run: |
      #     docker run --rm -t -v ${{ github.workspace }}/container/test-instances:/tests --env-file .env ${{ github.repository }}:latest /tests/hc-power-11.col /tests/hc-power-11_01.dat > hc-power-11-result.txt
      # - name: Set up validator
      #   run: |
      #     curl -fL https://raw.githubusercontent.com/core-challenge/isr-validator/main/main.py -o validator.py
      # - name: Validate result
      #   run: |
      #     python validator.py /tests/hc-power-11.col /tests/hc-power-11_01.dat hc-power-11-result.txt
      - name: Run test suite
        run: |
          ${{ github.workspace }}/.github/workflows/run-tests.sh $TIMEOUT solver:latest .env ${{ github.workspace }}/container/test-instances results
          cat results/ressult.md >> $GITHUB_STEP_SUMMARY
        env:
          TIMEOUT: 30

  test-description:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: description
          root_file: main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: Description
          path: description/main.pdf
