name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker container
          uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ github.action_repository }}:latest
      - name: Test container with simple dataset
        run: |
          docker run --rm -t ${{ github.action_repository }}:latest input.col input.dat

  test-description:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      # setup latex env
      # run pdflatex
